# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# Mod Versions
mod_version=0.5.2
artifact_minecraft_version=1.20.1
minecraft_version=1.20.1
forge_version=47.1.33
# Build Dependency Versions
mixin_version=0.8.5
parchment_version=2023.09.03
# Create Dependency Versions
create_minecraft_version=1.20.1
create_version=6.0.8
create_version_number=291
flywheel_minecraft_version=1.20.1
flywheel_version=1.0.6-beta-266
registrate_version=MC1.20-1.3.3
ponder_version=1.0.91
# TiC Dependencies Versions
tinker_version=3.11.2.166
mantle_version=1.11.104
# Optional Dependencies Versions
# JEI
jei_minecraft_version=1.20.1
jei_version=15.20.0.112
# Create Extensions
# https://modrinth.com/mod/create-metallurgy/versions
metallurgy_version=0.0.7-HF-1.20.1
# https://modrinth.com/mod/createaddition/versions
createaddition_version=9LgyB6Yb
# https://modrinth.com/mod/create-alloyed/versions
alloyed_version=2.1.3+1.20.1
# https://modrinth.com/mod/create-henry
create_henry_version=0.0.4-6.0
# https://modrinth.com/mod/create-enchantment-industry/versions
create_enchantment_industry_version=1.3.3
# https://modrinth.com/mod/create-cyber-goggles
goggles_version=1.20.1-6.7.8-Forge
# https://www.curseforge.com/minecraft/mc-mods/more-create-burners
burners_version=7395216
# https://modrinth.com/mod/create-new-age
new_age_version=zQStvTFw
# https://modrinth.com/mod/create-low-heated
create_low_heated_version=1.20.1-6.0.8-4
# TiC Extensions
tinkers_calibration_version=6809035
# Others
mekanism_version=1.20.1-10.4.9.61
mmet_version=v1.20.1-2.0.4-forge
cloth_config_version=11.1.136
